app-dev:
	uvicorn candlestick_api:app --host 127.0.0.1 --port 8000 --reload
app-prod:
	uvicorn candlestick_api:app --host 0.0.0.0
install:
	pip install -r requirements.txt
# env:
# 	source ./bool-env/bin/activate # activate env
# denv:
# 	deactivate
